apiVersion: v1
kind: Service
metadata:
  name: node-converter
  namespace: schema-converter
spec:
  selector:
    app: node-converter
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
