apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: schema-converter
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
